name: Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract environment and image values
      id: extract
      run: |
        # Extract the pull request body
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "Pull Request Body:"
        echo "$PR_BODY"

        # Extract the selected environment
        ENVIRONMENT=$(echo "$PR_BODY" | grep -oP '(?<=\[\s*x\s*\]\s).*')
        echo "Selected Environment: $ENVIRONMENT"

        # Initialize variables
        AP_IMAGE=""
        EU_IMAGE=""
        US_IMAGE=""

        # Extract image values based on the selected environment
        if [[ "$ENVIRONMENT" == "Dev" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*AP Region:\*\*\s*- Image:).+')
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*EU Region:\*\*\s*- Image:).+')
          US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*US Region:\*\*\s*- Image:).+')
        else
          echo "Environment not supported or not selected correctly."
          exit 1
        fi

        # Debugging: Print extracted values
        echo "Extracted Images Before Trim: AP='$AP_IMAGE', EU='$EU_IMAGE', US='$US_IMAGE'"

        # Trim whitespace
        AP_IMAGE=$(echo "$AP_IMAGE" | xargs)
        EU_IMAGE=$(echo "$EU_IMAGE" | xargs)
        US_IMAGE=$(echo "$US_IMAGE" | xargs)

        # Debugging: Print final values
        echo "Final Images: AP='$AP_IMAGE', EU='$EU_IMAGE', US='$US_IMAGE'"

        # Validate values
        if [ -z "$ENVIRONMENT" ] || [ -z "$AP_IMAGE" ] || [ -z "$EU_IMAGE" ] || [ -z "$US_IMAGE" ]; then
          echo "Error: One or more required values are missing."
          exit 1
        fi

        # Set output variables
        echo "environment=$ENVIRONMENT" >> $GITHUB_ENV
        echo "ap_image=$AP_IMAGE" >> $GITHUB_ENV
        echo "eu_image=$EU_IMAGE" >> $GITHUB_ENV
        echo "us_image=$US_IMAGE" >> $GITHUB_ENV

    - name: Deploy to Dev
      if: env.environment == 'Dev'
      run: |
        echo "Deploying to Dev environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment commands here
