name: Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract environment and image values
      id: extract
      run: |
        # Extract the pull request body
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "Pull Request Body: $PR_BODY"  # Debugging: Print the PR body

        # Extract the selected environment
        ENVIRONMENT=$(echo "$PR_BODY" | grep -oP '(?<=\[x\] ).*')
        echo "Selected Environment: $ENVIRONMENT"  # Debugging: Print the selected environment

        # Initialize variables
        AP_IMAGE=""
        EU_IMAGE=""
        US_IMAGE=""

        # Regex patterns for extracting image values
        PATTERN_AP='(?<=### '"$ENVIRONMENT"' Environment[\s\S]*- \*\*AP Region:.*Image:\s)(.*)'
        PATTERN_EU='(?<=### '"$ENVIRONMENT"' Environment[\s\S]*- \*\*EU Region:.*Image:\s)(.*)'
        PATTERN_US='(?<=### '"$ENVIRONMENT"' Environment[\s\S]*- \*\*US Region:.*Image:\s)(.*)'

        # Extract image values based on the selected environment
        if [[ "$ENVIRONMENT" == "Dev" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_AP" | head -n 1)
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_EU" | head -n 1)
          US_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_US" | head -n 1)
        elif [[ "$ENVIRONMENT" == "Staging" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_AP" | head -n 1)
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_EU" | head -n 1)
          US_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_US" | head -n 1)
        elif [[ "$ENVIRONMENT" == "Preprod" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_AP" | head -n 1)
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_EU" | head -n 1)
          US_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_US" | head -n 1)
        elif [[ "$ENVIRONMENT" == "Prod" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_AP" | head -n 1)
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_EU" | head -n 1)
          US_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_US" | head -n 1)
        elif [[ "$ENVIRONMENT" == "Staging_Production" ]]; then
          AP_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_AP" | head -n 1)
          EU_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_EU" | head -n 1)
          US_IMAGE=$(echo "$PR_BODY" | grep -oP "$PATTERN_US" | head -n 1)
        fi

        # Print extracted image values
        echo "AP Image: '$AP_IMAGE'"  # Debugging: Print the extracted AP image value
        echo "EU Image: '$EU_IMAGE'"  # Debugging: Print the extracted EU image value
        echo "US Image: '$US_IMAGE'"  # Debugging: Print the extracted US image value
        
        # Check if environment and image values were extracted correctly
        if [ -z "$ENVIRONMENT" ] || [ -z "$AP_IMAGE" ] || [ -z "$EU_IMAGE" ] || [ -z "$US_IMAGE" ]; then
          echo "Error: One or more values are empty."
          exit 1
        fi

        # Set the output variables for the deployment steps using Environment Files
        echo "environment=$ENVIRONMENT" >> $GITHUB_ENV
        echo "ap_image=$AP_IMAGE" >> $GITHUB_ENV
        echo "eu_image=$EU_IMAGE" >> $GITHUB_ENV
        echo "us_image=$US_IMAGE" >> $GITHUB_ENV

    - name: Deploy to Dev
      if: env.environment == 'Dev'
      run: |
        echo "Deploying to Dev environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment script/commands here

    - name: Deploy to Staging
      if: env.environment == 'Staging'
      run: |
        echo "Deploying to Staging environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment script/commands here

    - name: Deploy to Preprod
      if: env.environment == 'Preprod'
      run: |
        echo "Deploying to Preprod environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment script/commands here

    - name: Deploy to Prod
      if: env.environment == 'Prod'
      run: |
        echo "Deploying to Prod environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment script/commands here

    - name: Deploy to Staging_Production
      if: env.environment == 'Staging_Production'
      run: |
        echo "Deploying to Staging_Production environment"
        echo "AP Region Image: ${{ env.ap_image }}"
        echo "EU Region Image: ${{ env.eu_image }}"
        echo "US Region Image: ${{ env.us_image }}"
        # Add your deployment script/commands here